#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    printf "\033[0;30m\033[41mCOMMIT FAILED:\033[0m\n"
    printf "\t\033[31myour commit message is invalid\033[0m\n" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    printf "\033[0;30m\033[41mCOMMIT FAILED:\033[0m\n"
    printf "\t\033[31myour commit message is too long\033[0m\n" >&2
    exit 1
fi
