#!/bin/bash

# STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
STAGED_GO_FILES=$(git diff --cached --name-status --diff-filter d -- '*.go' | awk '{ print $2 }')

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

STATICCHECK=$GOPATH/bin/staticcheck
GOIMPORTS=$GOPATH/bin/goimports

# Check for staticcheck
if [[ ! -x "$STATICCHECK" ]]; then
  printf "\t\033[41mPlease install staticcheck\033[0m (go install honnef.co/go/tools/cmd/staticcheck@latest)"
  exit 1
fi

# Check for goimports
if [[ ! -x "$GOIMPORTS" ]]; then
  printf "\t\033[41mPlease install goimports\033[0m (go install golang.org/x/tools/cmd/goimports@latest)"
  exit 1
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
  # Run goimports and formatting on the staged file
  $GOIMPORTS -w $FILE
  gofmt -w $FILE
  git add $FILE

  # Run staticcheck on the staged file and check the exit status
  $STATICCHECK $FILE
  if [[ $? == 1 ]]; then
    printf "\t\033[31mstaticcheck $FILE\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
    PASS=false
  else
    printf "\t\033[32mstaticcheck $FILE\033[0m \033[0;30m\033[42mpass\033[0m\n"
  fi

  # Run govet on the staged file and check the exit status
  go vet $FILE
  if [[ $? != 0 ]]; then
    printf "\t\033[31mgo vet $FILE\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
    PASS=false
  else
    printf "\t\033[32mgo vet $FILE\033[0m \033[0;30m\033[42mpass\033[0m\n"
  fi
done

if ! $PASS; then
  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
  exit 1
else
  printf "\033[0;30m\033[42mGOFMT, GOIMPORTS, GOVET, STATICCHECK SUCCEEDED\033[0m\n"
fi

exit 0